In [27]:
import numpy as np

a = np.random.randn(1,3)
b = np.amax(a, axis=0, initial=0)
print(a, b, np.mean(b))

[[ 0.95500772 -1.68366602 -0.56869165]] [0.95500772 0.         0.        ] 0.31833590819904006


In [48]:
a = np.array([-1, 1])
b = np.array([[1, 1], [2, 2]])

print(a.shape)
a.shape = (2,1)
print(b.shape)
print(a.shape, np.transpose(a).shape, b.shape)
print(a, np.transpose(a))

c = np.transpose(a) @ b
d = np.dot(np.transpose(a), b)

print(c, d)

(2,)
(2, 2)
(2, 1) (1, 2) (2, 2)
[[-1]
 [ 1]] [[-1  1]]
[[1 1]] [[1 1]]


In [50]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


ModuleNotFoundError: No module named '__file__'